services:
  postgres:
    image: postgres:16
    container_name: ipove-postgres
    environment:
      POSTGRES_DB: ipove_dev
      POSTGRES_USER: ipove
      POSTGRES_PASSWORD: ipove_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ipove -d ipove_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ipove-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ipove-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ipove
      RABBITMQ_DEFAULT_PASS: ipove_secret
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: ipove-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak/ipove-realm.json:/opt/keycloak/data/import/ipove-realm.json:ro
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
