spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ipove_dev
    username: ipove
    password: ipove_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: ipove
    password: ipove_secret

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ipove-platform

ipove:
  notifications:
    email:
      enabled: false
      provider: console
    sms:
      enabled: false
      provider: console

logging:
  level:
    ai.ipove: DEBUG
